// <auto-generated />
namespace TrueMoney.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Renamed_BankAccountNumber_To_CardNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Renamed_BankAccountNumber_To_CardNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201612131441046_Renamed_BankAccountNumber_To_CardNumber"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
